/**
 * Designer help copy for DLG inspector fields.
 *
 * Intent is in-game use only (no engine internals).
 *
 * @file dlgInspectorHelp.ts
 * @author KobaltBlu <https://github.com/KobaltBlu>
 * @license {@link https://www.gnu.org/licenses/gpl-3.0.txt|GPLv3}
 */

export const DLG_HELP = {
  text: "Spoken line shown in the conversation window. Point at a talk table entry, or override with a custom string.",
  speaker: "Tag of the character who delivers this line. Leave blank for the conversation owner. OWNER and PLAYER are also accepted.",
  listener: "Who the speaker looks at and who the camera treats as the other person in the shot. OWNER is the conversation owner; PLAYER is the player. Blank uses a default listener.",
  comment: "Designer note only. Never shown in game.",
  unskippable: "Player cannot skip this line, even when the conversation itself is skippable.",
  voResRef: "Voice-over clip played with this line. If set, that file is used instead of generating a line from alien-voice tables.",
  sound: "Extra sound effect started with this line (separate from spoken VO).",
  emotion: "Mood used only to pick a foreign-language / alien voice clip when this line has no VO or extra sound. It does not change talk animations.",
  alienRaceNode: "Which alien-voice table row to use for this line. A value above none always wins. If none and this is an owner line, the conversation's Alien Race Owner is used.",
  facialAnim: "Stored on the line, but the game does not play it. Mouth movement comes from the LIP file that matches the voice clip.",
  recordVO: "Voice-recording note for the original toolset. The game ignores it while playing.",
  recordNoVOOverride: "Voice-recording note for the original toolset. The game ignores it while playing.",
  voTextChanged: "Voice-recording note for the original toolset. The game ignores it while playing.",
  script: "Script that runs when this line plays. Typically used for animations, increments, or other side effects.",
  script2: "Second action script for Knights of the Old Republic II. Both scripts run when the line plays.",
  paramNot: "Invert the script result. True becomes false, and false becomes true.",
  paramN: "Number passed into the matching script as a script parameter (1 through 5). Scripts read these with GetScriptParameter.",
  paramString: "String passed into the matching script along with the numeric parameters.",
  linkTarget: "Next line this reply or continue leads to. Order in the list is the on-screen order of player replies.",
  linkActive: "Condition script. If it returns false, this choice is hidden. Empty means the choice is always offered.",
  linkActive2: "Second condition for Knights of the Old Republic II. Combined with Active using Logic.",
  linkLogic: "How Active and Active2 combine when both are set. AND requires both true; OR requires either true. A single condition is evaluated on its own.",
  conversationType: "Normal spoken conversation vs a computer terminal panel. Computers swap the dialog UI and skip look-at / facing while the panel is open.",
  computerType: "Computer-screen backdrop (and related terminal look) from the computer types table. Only matters when this conversation is a computer.",
  voId: "Voice folder / recording ID for the conversation. Playback uses each line's VO clip, not this field.",
  cameraModel: "Camera model used for animated-cut shots. Named cut clips (cut001, cut002, …) are played from this model.",
  endConversation: "Script run when the conversation ends normally.",
  endAbort: "Script run when the conversation is cancelled or interrupted instead of finishing.",
  ambientTrack: "Music started for this conversation (typically a stream-music clip). Leave blank to keep the area music.",
  skippable: "Player can skip lines in this conversation, unless a line is marked unskippable.",
  animatedCut: "Play this conversation as an animated cutscene: stunt camera and stunt actor models, instead of ordinary talk shots.",
  unequipItems: "Hide weapons and other equipped hand items on participants for the conversation. They are restored when it ends.",
  unequipHeadItem: "Hide each participant's head item (mask, visor, and similar) for the conversation. Restored when it ends.",
  delayEntry: "Fallback wait before an NPC line continues, when that line does not set its own Delay. The game also uses spoken length when there is no voice file.",
  delayReply: "Fallback wait after a player reply before the next NPC line, when that reply does not set its own Delay.",
  alienRaceOwner: "Alien-voice table row used for owner lines that do not pick a race on the node. Ignored when the speaker is a tagged character with no node race.",
  postProcOwner: "Original toolset field. The game does not apply it while playing.",
  recordNoVO: "Voice-recording note for the original toolset. The game ignores it while playing.",
  oldHitCheck: "Original toolset field. The game does not use it while playing.",
  stuntParticipant: "Tag of the conversation participant who is replaced by a stunt model during an animated cut.",
  stuntModel: "Replacement model worn by that participant (body/stunt appearance) during the cutscene.",
  cameraAngle: "Shot type for this line: random, speaker close-up, over-the-shoulder, two-shot, animated cut camera, hold on listener, or a placed camera in the area.",
  cameraID: "Placed camera in the area. Only used when Angle is Placeable; other angles ignore this value.",
  cameraAnimation: "Animated-cut camera clip. 1000 plays cut001, 1001 plays cut002, and so on, on the conversation camera model. Use the Animated angle.",
  camFieldOfView: "Lens field of view for this shot, in degrees. Default lets the camera use its normal FOV.",
  camVidEffect: "Full-screen video look (scanlines, tint, and similar) from the video-effects table. None inherits; Disable turns the effect off. On computers, Disable (and effect 10) also hide the live camera feed.",
  animation: "Talk or gesture played on a participant during this line (listen, greet, and so on).",
  animParticipant: "Tag of who plays the animation. OWNER is the conversation owner; PLAYER is the player.",
  fadeType: "Screen fade with this line. None does nothing. Instant in/out snap to or from the fade color. Timed in/out blend over Fade Length after Fade Delay.",
  fadeLength: "How many seconds a timed fade takes. Instant fades always take no time.",
  fadeDelay: "Seconds to wait after the line starts before the fade begins.",
  fadeColor: "Color the screen fades to or from.",
  delay: "How long this line holds, in seconds, before continuing. Default lets the conversation defaults, voice length, or estimated read time decide. Animated cuts with no delay use no extra wait.",
  waitCamera: "Do not continue until this line's camera shot has finished.",
  waitVO: "Do not continue until the spoken voice-over has finished.",
  waitAnim: "Do not continue until this line's animations have finished.",
  waitFade: "Do not continue until the screen fade has finished.",
  waitExplicitDelay: "Honor this line's Delay even if spoken audio is missing. Without it, a missing voice clip falls back to an estimated read time.",
  quest: "Journal plot tag to update when this line plays. Blank means no journal change.",
  questEntry: "Journal state to set for that plot. Only advances if the player's current state is lower than this number.",
  plotIndex: "Plot table row that grants plot XP when this line plays. None grants nothing.",
  plotXPPct: "Portion of that plot's XP to award (1.00 is the full listed amount). No XP is given if this is zero or Plot Index is none.",
  postProcNode: "Original toolset field. The game does not apply it while playing.",
  delayUnset: "When on, this field uses the game default instead of a fixed number of seconds.",
  fovUnset: "When on, the camera keeps its normal field of view.",
} as const;
